### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.0 za namizja sistema Windows
  description: Microsoft Application Virtualization Hosting 5.0 za namizja sistema Windows sledi pravilniku o fiksnem življenjskem ciklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: dff04b865491bfb99aa8d20e556aafd434a59398
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: sl-SI
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "862967"
name: Microsoft Application Virtualization Hosting 5.0 za namizja sistema Windows
summary: >+
  Microsoft Application Virtualization Hosting 5.0 za namizja sistema Windows sledi pravilniku o [fiksnem](/lifecycle/policies/fixed) življenjskem ciklu.


  To velja za te izdaje: za namizja sistema Windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Service Pack 3
  startDate: 12/08/2014
  endDate: 04/14/2026
- version: Service Pack 2
  startDate: 11/08/2013
  endDate: 01/12/2016
- version: Service Pack 1
  startDate: 04/10/2013
  endDate: 01/13/2015
- version: Original Release
  startDate: 11/01/2012
  endDate: 07/08/2014
content: "\n## <a name=\"links\"></a>Povezave \n* [Informacije o izdelku](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Pravilnik o servisnem paketu](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Izdajah \n* za namizja sistema Windows"
