### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R2
  description: Microsoft System Center Configuration Manager 2007 R2 sledi fiksnemu pravilniku o 탑ivljenjskem ciklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: dc120aa48cf00c559b79cd24b31cde9a8122b573
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: sl-SI
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4106247"
name: Microsoft System Center Configuration Manager 2007 R2
summary: >
  Microsoft System Center Configuration Manager 2007 R2 sledi [fiksnemu ](/lifecycle/policies/fixed)pravilniku o 탑ivljenjskem ciklu.



  > [!IMPORTANT]

  > Podpora za ta izdelek je kon훾ana. Preberite spodnje smernice za selitev.
products:
- msc
policyType: fixed
supportDates:
  start: 2008-11-29T00:00:00.000-08:00
  end: 2014-07-08T22:59:59.999-08:00
  extendedEnd: 2019-07-09T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2008-11-29T00:00:00.000-08:00
  endDate: 2019-07-09T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Povezave \n* [Navodila za u훾inkovito selitev](/mem/configmgr/core/migration/planning-for-migration)\n* [Dodatne smernice za selitev](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
